### ISSUE TITLE
The example_frontalize_dlib_camera.py file does not seem to work

### ISSUE THREAD

**Issue by sjssjssjs** [bbonik/facial-landmark-frontalization#3]
Hi. Great work here. 

I have an issue with the example_frontalize_dlib_camera.py file.

The single picture version works however upon running the example_frontalize_dlib_camera.py no webcam light comes on, and I see the below blank screen.
![image](https://user-images.githubusercontent.com/7038426/120286190-5302ad00-c301-11eb-8b63-c33c1192a7b0.png)

Only when I press 'q' the window disappears and only then, the webcam light goes on and I see this...
![image](https://user-images.githubusercontent.com/7038426/120286260-657ce680-c301-11eb-9c41-b170b7c455a4.png)

Could you please show me what I am doing wrong? I am running the source code as is.

I would love to get a live stream of this frontalize animation from the webcam.

**Comment by bbonik** [comment]
Hi. Thank you for your interest in the project. This seems to be a problem of your camera's driver and OpenCV (which handles the communication with the camera). Since there is no light in your camera, it means that somehow the opencv camera object does not communicate with your camera as it should. Unfortunately I am not able to replicate your problem. In my Macbook it runs smoothly. What system are you running this on? 

In the past, in another Windows machine, I remember I had a similar problem with a different application, and the solution (hack) was to run that other application 2 times! First time start the app and kill it -> the camera light turned on -> second time start the app, allowing access to the (now on) camera. 

Can you try to rerun the script once your camera light is on (after you quit the first time)? Let me know how this goes...

**Comment by sjssjssjs** [comment]
Thank you so much for those suggestions. I will try it out with different
lighting conditions, and perhaps an external webcam. Interestingly I can
run all the other webcam Python examples which use webcam (0) and
dlib/opencv. I'll post how I go.
